# ========================
# zsh module loader
# ========================

typeset -g ZSH_HELPER_DIR="${${(%):-%N}:A:h}"

source "$ZSH_HELPER_DIR/creds-cli.zsh"
source "$ZSH_HELPER_DIR/wordlist.zsh"
source "$ZSH_HELPER_DIR/aliases.zsh"
source "$ZSH_HELPER_DIR/recon.zsh"
source "$ZSH_HELPER_DIR/cases.zsh"
source "$ZSH_HELPER_DIR/recon-target.zsh"
source "$ZSH_HELPER_DIR/hosts.zsh"
source "$ZSH_HELPER_DIR/recon-exec.zsh"
source "$ZSH_HELPER_DIR/recon-creds.zsh"
source "$ZSH_HELPER_DIR/recon-artifact.zsh"
source "$ZSH_HELPER_DIR/recon-exploit.zsh"
source "$ZSH_HELPER_DIR/recon-hint.zsh"
source "$ZSH_HELPER_DIR/probe.zsh"
source "$ZSH_HELPER_DIR/borg.zsh"
source "$ZSH_HELPER_DIR/encoding.zsh"
source "$ZSH_HELPER_DIR/exploit.zsh"
source "$ZSH_HELPER_DIR/external-tools.zsh"
source "$ZSH_HELPER_DIR/fixmagic.zsh"
source "$ZSH_HELPER_DIR/ftp.zsh"
source "$ZSH_HELPER_DIR/gobuster.zsh"
source "$ZSH_HELPER_DIR/hash.zsh"
source "$ZSH_HELPER_DIR/hydra.zsh"
source "$ZSH_HELPER_DIR/imgrpt.zsh"
source "$ZSH_HELPER_DIR/john.zsh"
source "$ZSH_HELPER_DIR/listeners.zsh"
source "$ZSH_HELPER_DIR/metasploit.zsh"
source "$ZSH_HELPER_DIR/pop3.zsh"
source "$ZSH_HELPER_DIR/repolog.zsh"
source "$ZSH_HELPER_DIR/reverse-shell.zsh"
source "$ZSH_HELPER_DIR/scan.zsh"
source "$ZSH_HELPER_DIR/scout.zsh"
source "$ZSH_HELPER_DIR/wp.zsh"
source "$ZSH_HELPER_DIR/ssh.zsh"
source "$ZSH_HELPER_DIR/steghide.zsh"
source "$ZSH_HELPER_DIR/strike.zsh"
source "$ZSH_HELPER_DIR/upload.zsh"
