# =====================
# basic
# =====================
set -g mouse on
set -g history-limit 50000
set -g default-terminal "screen-256color"
setw -g mode-keys vi

# =====================
# vi copy (Mac)
# =====================
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# =====================
# prefix
# =====================
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# =====================
# split
# =====================
bind s split-window -h
bind v split-window -v
unbind %
unbind '"'
unbind |

# =====================
# move
# =====================
bind j select-pane -L
bind k select-pane -D
bind i select-pane -U
bind l select-pane -R
bind -n M-Left  select-pane -L
bind -n M-Down  select-pane -D
bind -n M-Up    select-pane -U
bind -n M-Right select-pane -R

# =====================
# pane
# =====================
bind x kill-pane
bind z resize-pane -Z

# =====================
# reload
# =====================
bind r source-file ~/.tmux.conf \; display-message "reloaded"

# =====================
# plugins (TPM)
# =====================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'
run '~/.tmux/plugins/tpm/tpm'
